<a href="https://colab.research.google.com/github/vijay2107200/AI-Powered-Task-Management-System/blob/main/NLP-preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week-1 NLP-**preprocessing**
Project: AI-Powered Task Management System — Hospital Length of Stay Prediction Dataset: AV Healthcare Analytics II (Kaggle) Prepared by: Thivahar Balasubramaniam

In [16]:
import pandas as pd
import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [9]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

Saving train_clean.csv to train_clean (1).csv
User uploaded file "train_clean (1).csv" with length 25655738 bytes

### 1. "Loading dataset and initializing NLP preprocessing environment"

In [15]:
df = pd.read_csv('train_clean.csv')
display(df.head())

,case_id,Hospital,Hospital_type,Hospital_city,Hospital_region,Available_Extra_Rooms_in_Hospital,Department,Ward_Type,Ward_Facility,Bed_Grade,patientid,City_Code_Patient,Admission_Type,Illness_Severity,Patient_Visitors,Age,Admission_Deposit,Stay_Days
0,1,8,2,3,2,3,radiotherapy,R,F,2,31397,7,Emergency,Extreme,2,51-60,4911.0,0-10
1,2,2,2,5,2,2,radiotherapy,S,F,2,31397,7,Trauma,Extreme,2,51-60,5954.0,41-50
2,3,10,4,1,0,2,anesthesia,S,E,2,31397,7,Trauma,Extreme,2,51-60,4745.0,31-40
3,4,26,1,2,1,2,radiotherapy,R,D,2,31397,7,Trauma,Extreme,2,51-60,7272.0,41-50
4,5,26,1,2,1,2,radiotherapy,S,D,2,31397,7,Trauma,Extreme,2,51-60,5558.0,41-50

### 2.Selecting Text Columns

In [11]:
text_columns = [
    "Department",
    "Ward_Type",
    "Ward_Facility",
    "Admission_Type",
    "Illness_Severity",
    "Age",
    "Stay_Days"
]

df[text_columns].head()

,Department,Ward_Type,Ward_Facility,Admission_Type,Illness_Severity,Age,Stay_Days
0,radiotherapy,R,F,Emergency,Extreme,51-60,0-10
1,radiotherapy,S,F,Trauma,Extreme,51-60,41-50
2,anesthesia,S,E,Trauma,Extreme,51-60,31-40
3,radiotherapy,R,D,Trauma,Extreme,51-60,41-50
4,radiotherapy,S,D,Trauma,Extreme,51-60,41-50